"""Emission of a ready-to-run Vector pipeline carrying the VRL library.

The ``vector-enriched`` profile converts correlations that group on ``src_ip``,
``dest_ip`` or ``username``, but only because it assumes those fields exist.
Shipping the profile without the transforms that create them would produce
rules that validate cleanly and never fire, which is the failure mode this
project refuses everywhere else.

So the transforms travel with the rules. ``--emit-vector-config`` writes a
pipeline that is complete enough to start, and obvious enough about its two
placeholders that nobody starts it by accident.
"""

from __future__ import annotations

from importlib import resources
from pathlib import Path

_VRL_PACKAGE = "sagan2sigma.data.vrl"

#: Transforms shipped with the tool, in pipeline order.
TRANSFORMS: tuple[tuple[str, str], ...] = (
    (
        "sagan_parse_ip",
        "sagan-parse-ip.vrl",
    ),
    (
        "sagan_username",
        "username-extraction.vrl",
    ),
)

#: GeoIP country transform, inserted after ``sagan_parse_ip`` only when the
#: converted corpus uses ``country_code``. It is opt-in because it needs an
#: IP-to-country database present, without which Vector refuses to start.
GEOIP_TRANSFORM: tuple[str, str] = ("sagan_geoip", "sagan-geoip.vrl")

#: Weekday and hour-of-day transform, inserted only when the corpus uses
#: ``alert_time``. It has no external dependency, so it is omitted purely to
#: keep a pipeline that does not need it free of an unused step.
TIME_TRANSFORM: tuple[str, str] = ("sagan_time", "sagan-time.vrl")

#: Default IP-to-country database path in the emitted config. A placeholder: the
#: database is supplied by the user, so any provider's MMDB can be dropped in.
GEOIP_DATABASE_PATH = "/etc/vector/ip-to-country.mmdb"

# The ``mmdb`` table type, not ``geoip``: it returns the raw MMDB record for any
# MaxMind-format database regardless of its ``database_type``, so a MaxMind,
# DB-IP or IPLocate country database all work. The ``geoip`` type hard-codes the
# MaxMind schema and rejects the others. sagan-geoip.vrl reads the country code
# from whichever path the provider uses.
_ENRICHMENT_TABLES = """\
enrichment_tables:
  sagan_geoip:
    type: mmdb
    # CHANGE ME: path to an IP-to-country database in MaxMind MMDB format.
    # Any provider works; it is not bundled. See docs/PIPELINE.md for MaxMind
    # GeoLite2-Country, DB-IP IP-to-Country Lite and IPLocate download steps.
    path: {database}

"""

_CONFIG_TEMPLATE = """\
# Vector pipeline generated by sagan2sigma {version}.
#
# It recreates the fields Sagan derives from the raw message so that rules
# converted with --profile vector-enriched have something to group on.
#
# Two values below are placeholders and must be set before this runs:
#   * sources.appliances.address
#   * sinks.rsigma.uri
#
# Everything else is ready as-is. Check the pipeline before deploying it:
#
#     vector validate --config vector.yaml
#     vector vrl -i sample-events.json -p transforms/sagan-parse-ip.vrl -o

{enrichment}sources:
  appliances:
    type: syslog
    # CHANGE ME: the address and mode your appliances send to.
    address: 0.0.0.0:514
    mode: tcp

transforms:
{transforms}
sinks:
  rsigma:
    type: http
    inputs: [{last_transform}]
    # CHANGE ME: your RSigma ingest endpoint.
    uri: http://rsigma:8080/ingest
    encoding:
      codec: json
    # Sigma rules match one event at a time, so events are sent unbatched
    # rather than as a JSON array.
    framing:
      method: newline_delimited
"""

_TRANSFORM_BLOCK = """\
  {name}:
    type: remap
    inputs: [{previous}]
    file: transforms/{filename}
    # A malformed message must not drop the event: the enrichment is
    # best-effort and the detection rules still work without it.
    drop_on_error: false
"""


def read_transform(filename: str) -> str:
    """Return the text of a bundled VRL transform."""
    with (
        resources.files(_VRL_PACKAGE)
        .joinpath(filename)
        .open(encoding="utf-8") as handle
    ):
        return handle.read()


def _pipeline_transforms(geoip: bool, time: bool) -> tuple[tuple[str, str], ...]:
    """Transforms in pipeline order, optional ones inserted after IP parsing."""
    parse_ip, *rest = TRANSFORMS
    optional = [t for t, on in ((GEOIP_TRANSFORM, geoip), (TIME_TRANSFORM, time)) if on]
    return (parse_ip, *optional, *rest)


def build_config(
    version: str,
    source: str = "appliances",
    geoip: bool = False,
    time: bool = False,
) -> str:
    """Render the Vector configuration referencing every bundled transform.

    ``geoip`` adds the IP-to-country enrichment table and the country transform,
    and ``time`` the weekday-and-hour transform. Both are omitted otherwise so a
    pipeline that needs neither carries no unused step, and, for GeoIP, no
    database requirement.
    """
    blocks: list[str] = []
    previous = source
    for name, filename in _pipeline_transforms(geoip, time):
        blocks.append(
            _TRANSFORM_BLOCK.format(name=name, previous=previous, filename=filename)
        )
        previous = name
    enrichment = (
        _ENRICHMENT_TABLES.format(database=GEOIP_DATABASE_PATH) if geoip else ""
    )
    return _CONFIG_TEMPLATE.format(
        version=version,
        enrichment=enrichment,
        transforms="".join(blocks),
        last_transform=previous,
    )


def write_pipeline(
    output: Path, version: str, geoip: bool = False, time: bool = False
) -> list[Path]:
    """Write the configuration and the VRL transforms under ``output``.

    Returns the paths written, configuration first.
    """
    transforms_dir = output / "transforms"
    transforms_dir.mkdir(parents=True, exist_ok=True)

    config_path = output / "vector.yaml"
    config_path.write_text(
        build_config(version, geoip=geoip, time=time), encoding="utf-8"
    )

    written = [config_path]
    for _, filename in _pipeline_transforms(geoip, time):
        path = transforms_dir / filename
        path.write_text(read_transform(filename), encoding="utf-8")
        written.append(path)
    return written
