"""Emission of a ready-to-run Vector pipeline carrying the VRL library.

The ``vector-enriched`` profile converts constructs that need fields Sagan
derives from the raw message: correlations grouped on an address, GeoIP country,
a recurring time window, and threat-intel denylist or Zeek-intel membership. The
profile is only correct when the transforms that create those fields run, so the
transforms travel with the rules. ``--emit-vector-config`` writes a pipeline that
is complete enough to start and obvious about the placeholders it still needs.

The optional transforms are emitted only when the converted corpus uses the
construct they serve, so a pipeline is never made to carry an unused step, nor to
require a database it will never read.
"""

from __future__ import annotations

from dataclasses import dataclass
from importlib import resources
from pathlib import Path

_VRL_PACKAGE = "sagan2sigma.data.vrl"

#: Base transforms, always emitted. JSON handling first (it preserves the raw
#: body and lifts a JSON body's keys to the top level), then address parsing,
#: then username last.
_JSON: tuple[str, str] = ("sagan_json", "sagan-json.vrl")
_PARSE_IP: tuple[str, str] = ("sagan_parse_ip", "sagan-parse-ip.vrl")
_USERNAME: tuple[str, str] = ("sagan_username", "username-extraction.vrl")

#: The always-present transforms, kept as a name for tests and callers.
TRANSFORMS: tuple[tuple[str, str], ...] = (_JSON, _PARSE_IP, _USERNAME)

#: Default database paths in the emitted config. Placeholders: the databases are
#: supplied by the user, so any provider's or feed's MMDB can be dropped in.
GEOIP_DATABASE_PATH = "/etc/vector/ip-to-country.mmdb"
DENYLIST_DATABASE_PATH = "/etc/vector/denylist.mmdb"
ZEEK_DATABASE_PATH = "/etc/vector/zeek-intel.mmdb"
BLUEDOT_TOR_DATABASE_PATH = "/etc/vector/bluedot-tor.mmdb"


@dataclass(frozen=True)
class _Optional:
    """A transform inserted between IP parsing and username extraction.

    ``table`` is the mmdb enrichment table block it needs, already carrying a
    ``{path}`` placeholder, or ``None`` for a transform with no external data.
    """

    flag: str
    transform: tuple[str, str]
    table: str | None
    default_path: str


_GEOIP_TABLE = """\
  sagan_geoip:
    type: mmdb
    # CHANGE ME: path to an IP-to-country database in MaxMind MMDB format. The
    # mmdb table type reads any provider, so MaxMind GeoLite2-Country, DB-IP
    # IP-to-Country Lite and IPLocate all work. See docs/PIPELINE.md.
    path: {path}
"""

_DENYLIST_TABLE = """\
  sagan_denylist:
    type: mmdb
    # CHANGE ME: an IP denylist as a MaxMind-format MMDB, built from a feed such
    # as SANS DShield with tools/build_denylist_mmdb.py. See docs/PIPELINE.md.
    path: {path}
"""

_ZEEK_TABLE = """\
  sagan_zeek_intel:
    type: mmdb
    # CHANGE ME: a Zeek Intel feed as a MaxMind-format MMDB, built from a feed
    # such as CriticalPathSecurity's with tools/build_denylist_mmdb.py.
    path: {path}
"""

_BLUEDOT_TABLE = """\
  sagan_bluedot_tor:
    type: mmdb
    # CHANGE ME: open-source substitutes for Bluedot's categories, one MMDB each,
    # built with tools/build_denylist_mmdb.py. Tor is near-authoritative: use the
    # Tor Project exit-node list. The rest are your choice and diverge from
    # Bluedot (D_BLUEDOT_SUBSTITUTION). See docs/DESIGN-DECISIONS.md.
    path: {path}
  sagan_bluedot_proxy:
    type: mmdb
    path: /etc/vector/bluedot-proxy.mmdb
  sagan_bluedot_malicious:
    type: mmdb
    path: /etc/vector/bluedot-malicious.mmdb
  sagan_bluedot_honeypot:
    type: mmdb
    path: /etc/vector/bluedot-honeypot.mmdb
"""

#: Optional transforms, in pipeline order after ``sagan_parse_ip``.
_OPTIONALS: tuple[_Optional, ...] = (
    _Optional(
        "geoip", ("sagan_geoip", "sagan-geoip.vrl"), _GEOIP_TABLE, GEOIP_DATABASE_PATH
    ),
    _Optional(
        "denylist",
        ("sagan_denylist", "sagan-denylist.vrl"),
        _DENYLIST_TABLE,
        DENYLIST_DATABASE_PATH,
    ),
    _Optional(
        "zeek",
        ("sagan_zeek_intel", "sagan-zeek-intel.vrl"),
        _ZEEK_TABLE,
        ZEEK_DATABASE_PATH,
    ),
    _Optional(
        "bluedot",
        ("sagan_bluedot", "sagan-bluedot.vrl"),
        _BLUEDOT_TABLE,
        BLUEDOT_TOR_DATABASE_PATH,
    ),
    _Optional("time", ("sagan_time", "sagan-time.vrl"), None, ""),
)

_CONFIG_TEMPLATE = """\
# Vector pipeline generated by sagan2sigma {version}.
#
# It recreates the fields Sagan derives from the raw message so that rules
# converted with --profile vector-enriched have something to match on.
#
# Two values below are placeholders and must be set before this runs:
#   * sources.appliances.address
#   * sinks.rsigma.uri
# Any enrichment_tables below carry a database path placeholder too.
#
# Everything else is ready as-is. Check the pipeline before deploying it:
#
#     vector validate --config vector.yaml
#     vector vrl -i sample-events.json -p transforms/sagan-parse-ip.vrl -o

{enrichment}sources:
  appliances:
    type: syslog
    # CHANGE ME: the address and mode your appliances send to.
    address: 0.0.0.0:514
    mode: tcp

transforms:
{transforms}
sinks:
  rsigma:
    type: http
    inputs: [{last_transform}]
    # CHANGE ME: your RSigma ingest endpoint.
    uri: http://rsigma:8080/ingest
    encoding:
      codec: json
    # Sigma rules match one event at a time, so events are sent unbatched
    # rather than as a JSON array.
    framing:
      method: newline_delimited
"""

_TRANSFORM_BLOCK = """\
  {name}:
    type: remap
    inputs: [{previous}]
    file: transforms/{filename}
    # A malformed message must not drop the event: the enrichment is
    # best-effort and the detection rules still work without it.
    drop_on_error: false
"""


def read_transform(filename: str) -> str:
    """Return the text of a bundled VRL transform."""
    with (
        resources.files(_VRL_PACKAGE)
        .joinpath(filename)
        .open(encoding="utf-8") as handle
    ):
        return handle.read()


def _enabled(flags: dict[str, bool]) -> list[_Optional]:
    """Optional transforms turned on, in pipeline order."""
    return [option for option in _OPTIONALS if flags.get(option.flag)]


def _pipeline_transforms(flags: dict[str, bool]) -> list[tuple[str, str]]:
    """Every transform to write, in pipeline order."""
    return [
        _JSON,
        _PARSE_IP,
        *(option.transform for option in _enabled(flags)),
        _USERNAME,
    ]


def build_config(
    version: str,
    source: str = "appliances",
    geoip: bool = False,
    time: bool = False,
    denylist: bool = False,
    zeek: bool = False,
    bluedot: bool = False,
) -> str:
    """Render the Vector configuration referencing every needed transform.

    Each optional transform, and its enrichment table when it has one, is added
    only when its flag is set, so a pipeline that needs none of them carries no
    unused step and no database requirement.
    """
    flags = {
        "geoip": geoip,
        "denylist": denylist,
        "zeek": zeek,
        "bluedot": bluedot,
        "time": time,
    }

    blocks: list[str] = []
    previous = source
    for name, filename in _pipeline_transforms(flags):
        blocks.append(
            _TRANSFORM_BLOCK.format(name=name, previous=previous, filename=filename)
        )
        previous = name

    tables = [
        option.table.format(path=option.default_path)
        for option in _enabled(flags)
        if option.table is not None
    ]
    enrichment = "enrichment_tables:\n" + "".join(tables) + "\n" if tables else ""

    return _CONFIG_TEMPLATE.format(
        version=version,
        enrichment=enrichment,
        transforms="".join(blocks),
        last_transform=previous,
    )


def write_pipeline(
    output: Path,
    version: str,
    geoip: bool = False,
    time: bool = False,
    denylist: bool = False,
    zeek: bool = False,
    bluedot: bool = False,
) -> list[Path]:
    """Write the configuration and the VRL transforms under ``output``.

    Returns the paths written, configuration first.
    """
    flags = {
        "geoip": geoip,
        "denylist": denylist,
        "zeek": zeek,
        "bluedot": bluedot,
        "time": time,
    }

    transforms_dir = output / "transforms"
    transforms_dir.mkdir(parents=True, exist_ok=True)

    config_path = output / "vector.yaml"
    config_path.write_text(
        build_config(
            version,
            geoip=geoip,
            time=time,
            denylist=denylist,
            zeek=zeek,
            bluedot=bluedot,
        ),
        encoding="utf-8",
    )

    written = [config_path]
    for _, filename in _pipeline_transforms(flags):
        path = transforms_dir / filename
        path.write_text(read_transform(filename), encoding="utf-8")
        written.append(path)
    return written
